### ISSUE TITLE
Important_changes.md needs updates for 7.22.1 and 7.22.2

### ISSUE THREAD

**Issue by drzwave** [SiliconLabs/simplicity_sdk#24]
protocol/z-wave/docs_public/important_changes.md has the 7.22.0 as the "latest".

Specifically, is EULR out of Alpha in 7.22.2? Hopefully GA but at least Beta??? Does it work???

I'd like to test it at UnPlugFest in Barcelona in Feb 2025.

**Comment by zackbcom** [comment]
Looks like it's in GA for 7.23.0 GA that just came out.
https://github.com/SiliconLabs/simplicity_sdk/blob/sisdk-2024.12/protocol/z-wave/docs_public/important_changes.md

[7.23.0 Release Notes](https://www.silabs.com/documents/public/release-notes/SRN14930-7.23.0.0.pdf)
> 2.1 New Items
> • The Z-Wave Long Range EU region is officially supported.
> • Security S2V2 is introduced as an Alpha feature. S2V2 enables secure communication for network frames in a Z-Wave network

**Comment by drzwave** [comment]
finally!
